import type { Asset } from '../interfaces/types';

/**
 * Stable opaque string identifier for a {@link Position}. Generated by the
 * SDK when a position is opened; callers should treat this as an opaque key
 * and not parse its contents.
 */
export type PositionId = string;

/**
 * A single open position in an asset.
 *
 * `basis` tracks the total cost of the position (including fees) and is used
 * for realized P&L calculations. It is updated by `applyFills` as the
 * position is added to or reduced.
 *
 * @example
 * ```ts
 * import type { Position } from '@livefolio/sdk';
 *
 * const pos: Position = {
 *   id:       'pos_1',
 *   asset:    { kind: 'equity', id: 'AAPL', symbol: 'AAPL' },
 *   side:     'long',
 *   quantity: 100,
 *   entry:    { date: new Date('2024-01-02'), price: 185.5 },
 *   basis:    18_550.50,  // quantity * price + fees
 *   tags:     { strategy: 'momentum' },
 * };
 * ```
 */
export type Position = {
  /** Stable opaque ID assigned when the position was opened. */
  id: PositionId;
  asset: Asset;
  side: 'long' | 'short';
  /** Current number of shares (or units) held. */
  quantity: number;
  /** Price and date at which this position lot was initially opened. */
  entry: { date: Date; price: number };
  /**
   * Total cost basis of the current quantity in base currency
   * (fill price × shares + fees at entry, adjusted on partial closes).
   */
  basis: number;
  /** Optional key-value labels for strategy attribution or downstream reporting. */
  tags?: Record<string, unknown>;
};

/**
 * A point-in-time snapshot of the full portfolio state.
 *
 * `t` advances to the latest fill timestamp each time {@link applyFills} is
 * called. It is used as the portfolio's logical "now" for downstream
 * computations.
 *
 * @example
 * ```ts
 * import type { Portfolio } from '@livefolio/sdk';
 *
 * const portfolio: Portfolio = {
 *   cash:      50_000,
 *   positions: [],
 *   t:         new Date('2024-01-01'),
 * };
 * ```
 */
export type Portfolio = {
  /** Uninvested cash in the portfolio's base currency. */
  cash: number;
  /** All currently open positions. Immutable array — replaced (not mutated) by apply functions. */
  positions: ReadonlyArray<Position>;
  /** Logical timestamp of the most recent fill (or the portfolio's start date). */
  t: Date;
};
