import type { Asset } from '../interfaces/types';

/**
 * Stable opaque string identifier for a {@link Position}. Generated by the
 * SDK when a position is opened; callers should treat this as an opaque key
 * and not parse its contents.
 */
export type PositionId = string;

/**
 * A single open position in an asset.
 *
 * `basis` tracks the total cost of the position (including fees) and is used
 * for realized P&L calculations. It is updated by `applyFills` as the
 * position is added to or reduced.
 *
 * @example
 * ```ts
 * import type { Position } from '@livefolio/sdk';
 *
 * const pos: Position = {
 *   id:       'pos_1',
 *   asset:    { kind: 'equity', id: 'AAPL', symbol: 'AAPL' },
 *   side:     'long',
 *   quantity: 100,
 *   entry:    { date: new Date('2024-01-02'), price: 185.5 },
 *   basis:    18_550.50,  // quantity * price + fees
 *   tags:     { strategy: 'momentum' },
 * };
 * ```
 */
export type Position = {
  /** Stable opaque ID assigned when the position was opened. */
  id: PositionId;
  asset: Asset;
  side: 'long' | 'short';
  /** Current number of shares (or units) held. */
  quantity: number;
  /** Price and date at which this position lot was initially opened. */
  entry: { date: Date; price: number };
  /**
   * Total cost basis of the current quantity in base currency
   * (fill price × shares + fees at entry, adjusted on partial closes).
   */
  basis: number;
  /** Optional key-value labels for strategy attribution or downstream reporting. */
  tags?: Record<string, unknown>;
};

/**
 * Tax classification of a {@link RealizedEvent}. Drives which rate bucket the
 * income falls into during year-level tax aggregation.
 */
export type IncomeKind = 'capital-gain' | 'qualified-dividend' | 'ordinary-dividend' | 'interest';

/**
 * A single tax lot — one acquisition of `quantity` shares of `asset` at a
 * point in time. The cost-basis source of truth for long holdings. Partial
 * sales reduce `quantity` and pro-rate `basis`.
 */
export type Lot = {
  /** Opaque id assigned by `nextLotId` on creation. */
  id: string;
  asset: Asset;
  /** Shares remaining in this lot after any partial sales. */
  quantity: number;
  /** Date the lot was opened (a DRIP lot's clock starts at its pay date). */
  openDate: Date;
  /** Per-share open price, excluding fees. */
  openPrice: number;
  /** Total cost basis for `quantity` shares incl. entry fees; pro-rated on partial sale and bumped by wash-sale §1091. */
  basis: number;
  /** Running total of disallowed wash-sale losses absorbed into `basis`. */
  washSaleAdjustment?: number;
  /** Set when this lot was created via dividend reinvestment; references the lot whose dividend funded it. */
  dripParent?: string;
};

/**
 * An append-only record of realized taxable activity: a capital gain/loss from
 * closing (part of) a lot, or dividend/interest income. `quantity` is `0` for
 * income events (dividends, interest), which carry `basis: 0` and `gain = proceeds`.
 */
export type RealizedEvent = {
  asset: Asset;
  /** The lot this event closed against. For income events, a reference token (e.g. the paying lot, or `'cash'` for interest). */
  lotId: string;
  quantity: number;
  openDate: Date;
  closeDate: Date;
  proceeds: number;
  basis: number;
  termType: 'short' | 'long';
  gain: number;
  incomeKind: IncomeKind;
  /** When `> 0`, this much of a (negative) capital gain was disallowed by the wash-sale rule and rolled into a replacement lot's basis. */
  washSaleDisallowed?: number;
};

/**
 * A point-in-time snapshot of the full portfolio state.
 *
 * `t` advances to the latest fill timestamp each time {@link applyFills} is
 * called. It is used as the portfolio's logical "now" for downstream
 * computations.
 *
 * @example
 * ```ts
 * import type { Portfolio } from '@livefolio/sdk';
 *
 * const portfolio: Portfolio = {
 *   cash:      50_000,
 *   positions: [],
 *   t:         new Date('2024-01-01'),
 * };
 * ```
 */
export type Portfolio = {
  /** Uninvested cash in the portfolio's base currency. */
  cash: number;
  /** All currently open positions. Immutable array — replaced (not mutated) by apply functions. */
  positions: ReadonlyArray<Position>;
  /**
   * Long-side tax ledger — the cost-basis source of truth for lot accounting.
   * Maintained in parallel with `positions` by `applyFills`; defaults to `[]`
   * when absent. Short positions and `adjust` orders do not participate.
   */
  lots?: ReadonlyArray<Lot>;
  /**
   * Append-only log of realized capital gains and dividend/interest income
   * accumulated during a run. Defaults to `[]` when absent.
   */
  realized?: ReadonlyArray<RealizedEvent>;
  /** Logical timestamp of the most recent fill (or the portfolio's start date). */
  t: Date;
};
