create table "trading_days"
(
    "id"        bigint generated by default as identity primary key,
    "date"      date        not null unique,
    "overnight" timestamptz not null,
    "pre"       timestamptz not null,
    "regular"   timestamptz not null,
    "post"      timestamptz not null,
    "close"     timestamptz not null
);

CREATE INDEX ON trading_days USING btree (post);
CREATE INDEX ON trading_days USING btree (close);

ALTER TABLE trading_days ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON trading_days FOR SELECT USING (true);
