create table "tickers"
(
    "id"       bigint generated by default as identity primary key,
    "symbol"     text                     not null,
    "leverage"   numeric                  not null,
    "created_at" timestamptz default now() not null,

    constraint tickers_symbol_leverage_key unique (symbol, leverage)
);

ALTER TABLE tickers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON tickers FOR SELECT USING (true);