create type indicator_type as enum (
    'SMA',
    'EMA',
    'Price',
    'Return',
    'Volatility',
    'Drawdown',
    'RSI',
    'VIX',
    'VIX3M',
    'T3M',
    'T6M',
    'T1Y',
    'T2Y',
    'T3Y',
    'T5Y',
    'T7Y',
    'T10Y',
    'T20Y',
    'T30Y',
    'Month',
    'Day of Week',
    'Day of Month',
    'Day of Year',
    'Threshold'
    );

create type unit as enum ('%', '$');

create table "indicators"
(
    "id"        bigint generated by default as identity primary key,
    "type"      indicator_type not null,
    "ticker_id" bigint references tickers (id) on delete restrict,
    "lookback"  int            not null,
    "delay"     int            not null,
    "unit"      unit,
    "threshold"  numeric,
    "created_at" timestamptz default now() not null,

    constraint indicators_identity_key
        unique nulls not distinct (type, ticker_id, lookback, delay, unit, threshold)
);

ALTER TABLE indicators ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON indicators FOR SELECT USING (true);

-- Indicators Series

create table indicators_series
(
    id             bigint generated by default as identity primary key,
    indicator_id   bigint      not null references indicators (id) on delete cascade,
    trading_day_id bigint      not null references trading_days (id) on delete cascade,
    "value"          numeric     not null,
    metadata       jsonb,
    constraint unique_indicator_eval_per_day unique (indicator_id, trading_day_id)
);

CREATE INDEX ON indicators_series USING btree (indicator_id);
CREATE INDEX ON indicators_series USING btree (trading_day_id);

ALTER TABLE indicators_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON indicators_series FOR SELECT USING (true);
