create type comparison as enum ('>', '<', '=');

create table signals
(
    "id"             bigint generated by default as identity primary key,
    "indicator_id_1" bigint     not null references indicators (id) on delete cascade,
    "indicator_id_2" bigint     not null references indicators (id) on delete cascade,
    "comparison"     comparison not null,
    "tolerance"      numeric    not null,
    "created_at"     timestamptz default now() not null,
    constraint unique_signal_definition unique (indicator_id_1, indicator_id_2, comparison, tolerance)
);

ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON signals FOR SELECT USING (true);

-- Signals Series

create table signals_series
(
    id             bigint generated by default as identity primary key,
    signal_id      bigint      not null references signals (id) on delete cascade,
    trading_day_id bigint      not null references trading_days (id) on delete cascade,
    "value"          boolean     not null,
    constraint unique_signal_eval_per_day unique (signal_id, trading_day_id)
);

CREATE INDEX ON signals_series USING btree (signal_id);

ALTER TABLE signals_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON signals_series FOR SELECT USING (true);
