create table allocations
(
    "id"         bigint generated by default as identity primary key,
    "holdings"   jsonb not null,
    "created_at" timestamptz default now() not null
);

CREATE INDEX idx_allocations_holdings ON allocations USING GIN (holdings);

ALTER TABLE allocations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON allocations FOR SELECT USING (true);
