create type trading_freq as enum
(
    'Daily',
    'Weekly',
    'Monthly',
    'Bi-monthly',
    'Quarterly',
    'Every 4 Months',
    'Semiannually',
    'Yearly'
);

create table strategies
(
    "id"                bigint generated by default as identity primary key,
    "link_id"           text not null unique,
    "name"              text not null,
    "trading_freq"      trading_freq not null default 'Daily',
    "trading_offset"    int not null default 0,
    "definition"        jsonb,
    "created_at"        timestamptz default now() not null
);

CREATE INDEX idx_strategies_definition ON strategies USING GIN (definition);

ALTER TABLE strategies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON strategies FOR SELECT USING (true);

-- Strategies Series

create table strategies_series
(
    id             bigint generated by default as identity primary key,
    strategies_id      bigint      not null references strategies (id) on delete cascade,
    trading_day_id bigint      not null references trading_days (id) on delete cascade,
    allocation_id          bigint     not null references allocations (id) on delete cascade,
    constraint unique_strategies_eval_per_day unique (strategies_id, trading_day_id)
);

CREATE INDEX ON strategies_series USING btree (strategies_id);

ALTER TABLE strategies_series ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON strategies_series FOR SELECT USING (true);
