
  create table "public"."signals_series" (
    "id" bigint generated by default as identity not null,
    "signal_id" bigint not null,
    "trading_day_id" bigint not null,
    "value" boolean not null
      );


CREATE UNIQUE INDEX signals_series_pkey ON public.signals_series USING btree (id);

CREATE INDEX signals_series_signal_id_idx ON public.signals_series USING btree (signal_id);

CREATE UNIQUE INDEX unique_signal_eval_per_day ON public.signals_series USING btree (signal_id, trading_day_id);

alter table "public"."signals_series" add constraint "signals_series_pkey" PRIMARY KEY using index "signals_series_pkey";

alter table "public"."signals_series" add constraint "signals_series_signal_id_fkey" FOREIGN KEY (signal_id) REFERENCES public.signals(id) ON DELETE CASCADE not valid;

alter table "public"."signals_series" validate constraint "signals_series_signal_id_fkey";

alter table "public"."signals_series" add constraint "signals_series_trading_day_id_fkey" FOREIGN KEY (trading_day_id) REFERENCES public.trading_days(id) ON DELETE CASCADE not valid;

alter table "public"."signals_series" validate constraint "signals_series_trading_day_id_fkey";

alter table "public"."signals_series" add constraint "unique_signal_eval_per_day" UNIQUE using index "unique_signal_eval_per_day";

grant delete on table "public"."signals_series" to "anon";

grant insert on table "public"."signals_series" to "anon";

grant references on table "public"."signals_series" to "anon";

grant select on table "public"."signals_series" to "anon";

grant trigger on table "public"."signals_series" to "anon";

grant truncate on table "public"."signals_series" to "anon";

grant update on table "public"."signals_series" to "anon";

grant delete on table "public"."signals_series" to "authenticated";

grant insert on table "public"."signals_series" to "authenticated";

grant references on table "public"."signals_series" to "authenticated";

grant select on table "public"."signals_series" to "authenticated";

grant trigger on table "public"."signals_series" to "authenticated";

grant truncate on table "public"."signals_series" to "authenticated";

grant update on table "public"."signals_series" to "authenticated";

grant delete on table "public"."signals_series" to "service_role";

grant insert on table "public"."signals_series" to "service_role";

grant references on table "public"."signals_series" to "service_role";

grant select on table "public"."signals_series" to "service_role";

grant trigger on table "public"."signals_series" to "service_role";

grant truncate on table "public"."signals_series" to "service_role";

grant update on table "public"."signals_series" to "service_role";


