create type "public"."indicator_type" as enum ('SMA', 'EMA', 'Price', 'Return', 'Volatility', 'Drawdown', 'RSI', 'VIX', 'VIX3M', 'T3M', 'T6M', 'T1Y', 'T2Y', 'T3Y', 'T5Y', 'T7Y', 'T10Y', 'T20Y', 'T30Y', 'Month', 'Day of Week', 'Day of Month', 'Day of Year', 'Threshold');

create type "public"."unit" as enum ('%', '$');


  create table "public"."indicators" (
    "id" bigint generated by default as identity not null,
    "type" public.indicator_type not null,
    "ticker_id" bigint,
    "lookback" integer not null,
    "delay" integer not null,
    "unit" public.unit,
    "threshold" numeric
      );


CREATE UNIQUE INDEX indicators_identity_key ON public.indicators USING btree (type, ticker_id, lookback, delay, unit, threshold) NULLS NOT DISTINCT;

CREATE UNIQUE INDEX indicators_pkey ON public.indicators USING btree (id);

alter table "public"."indicators" add constraint "indicators_pkey" PRIMARY KEY using index "indicators_pkey";

alter table "public"."indicators" add constraint "indicators_identity_key" UNIQUE using index "indicators_identity_key";

alter table "public"."indicators" add constraint "indicators_ticker_id_fkey" FOREIGN KEY (ticker_id) REFERENCES public.tickers(id) ON DELETE RESTRICT not valid;

alter table "public"."indicators" validate constraint "indicators_ticker_id_fkey";

grant delete on table "public"."indicators" to "anon";

grant insert on table "public"."indicators" to "anon";

grant references on table "public"."indicators" to "anon";

grant select on table "public"."indicators" to "anon";

grant trigger on table "public"."indicators" to "anon";

grant truncate on table "public"."indicators" to "anon";

grant update on table "public"."indicators" to "anon";

grant delete on table "public"."indicators" to "authenticated";

grant insert on table "public"."indicators" to "authenticated";

grant references on table "public"."indicators" to "authenticated";

grant select on table "public"."indicators" to "authenticated";

grant trigger on table "public"."indicators" to "authenticated";

grant truncate on table "public"."indicators" to "authenticated";

grant update on table "public"."indicators" to "authenticated";

grant delete on table "public"."indicators" to "service_role";

grant insert on table "public"."indicators" to "service_role";

grant references on table "public"."indicators" to "service_role";

grant select on table "public"."indicators" to "service_role";

grant trigger on table "public"."indicators" to "service_role";

grant truncate on table "public"."indicators" to "service_role";

grant update on table "public"."indicators" to "service_role";


