create type "public"."trading_freq" as enum ('Daily', 'Weekly', 'Monthly', 'Bi-monthly', 'Quarterly', 'Every 4 Months', 'Semiannually', 'Yearly');


  create table "public"."strategies" (
    "id" bigint generated by default as identity not null,
    "link_id" text not null,
    "name" text not null,
    "trading_freq" public.trading_freq not null default 'Daily'::public.trading_freq,
    "trading_offset" integer not null default 0,
    "definition" jsonb,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."strategies" enable row level security;

CREATE INDEX idx_strategies_definition ON public.strategies USING gin (definition);

CREATE UNIQUE INDEX strategies_link_id_key ON public.strategies USING btree (link_id);

CREATE UNIQUE INDEX strategies_pkey ON public.strategies USING btree (id);

alter table "public"."strategies" add constraint "strategies_pkey" PRIMARY KEY using index "strategies_pkey";

alter table "public"."strategies" add constraint "strategies_link_id_key" UNIQUE using index "strategies_link_id_key";

grant delete on table "public"."strategies" to "anon";

grant insert on table "public"."strategies" to "anon";

grant references on table "public"."strategies" to "anon";

grant select on table "public"."strategies" to "anon";

grant trigger on table "public"."strategies" to "anon";

grant truncate on table "public"."strategies" to "anon";

grant update on table "public"."strategies" to "anon";

grant delete on table "public"."strategies" to "authenticated";

grant insert on table "public"."strategies" to "authenticated";

grant references on table "public"."strategies" to "authenticated";

grant select on table "public"."strategies" to "authenticated";

grant trigger on table "public"."strategies" to "authenticated";

grant truncate on table "public"."strategies" to "authenticated";

grant update on table "public"."strategies" to "authenticated";

grant delete on table "public"."strategies" to "service_role";

grant insert on table "public"."strategies" to "service_role";

grant references on table "public"."strategies" to "service_role";

grant select on table "public"."strategies" to "service_role";

grant trigger on table "public"."strategies" to "service_role";

grant truncate on table "public"."strategies" to "service_role";

grant update on table "public"."strategies" to "service_role";


  create policy "public read"
  on "public"."strategies"
  as permissive
  for select
  to public
using (true);



