
  create table "public"."strategies_series" (
    "id" bigint generated by default as identity not null,
    "strategies_id" bigint not null,
    "trading_day_id" bigint not null,
    "allocation_id" bigint not null
      );


alter table "public"."strategies_series" enable row level security;

CREATE UNIQUE INDEX strategies_series_pkey ON public.strategies_series USING btree (id);

CREATE INDEX strategies_series_strategies_id_idx ON public.strategies_series USING btree (strategies_id);

CREATE UNIQUE INDEX unique_strategies_eval_per_day ON public.strategies_series USING btree (strategies_id, trading_day_id);

alter table "public"."strategies_series" add constraint "strategies_series_pkey" PRIMARY KEY using index "strategies_series_pkey";

alter table "public"."strategies_series" add constraint "strategies_series_allocation_id_fkey" FOREIGN KEY (allocation_id) REFERENCES public.allocations(id) ON DELETE CASCADE not valid;

alter table "public"."strategies_series" validate constraint "strategies_series_allocation_id_fkey";

alter table "public"."strategies_series" add constraint "strategies_series_strategies_id_fkey" FOREIGN KEY (strategies_id) REFERENCES public.strategies(id) ON DELETE CASCADE not valid;

alter table "public"."strategies_series" validate constraint "strategies_series_strategies_id_fkey";

alter table "public"."strategies_series" add constraint "strategies_series_trading_day_id_fkey" FOREIGN KEY (trading_day_id) REFERENCES public.trading_days(id) ON DELETE CASCADE not valid;

alter table "public"."strategies_series" validate constraint "strategies_series_trading_day_id_fkey";

alter table "public"."strategies_series" add constraint "unique_strategies_eval_per_day" UNIQUE using index "unique_strategies_eval_per_day";

grant delete on table "public"."strategies_series" to "anon";

grant insert on table "public"."strategies_series" to "anon";

grant references on table "public"."strategies_series" to "anon";

grant select on table "public"."strategies_series" to "anon";

grant trigger on table "public"."strategies_series" to "anon";

grant truncate on table "public"."strategies_series" to "anon";

grant update on table "public"."strategies_series" to "anon";

grant delete on table "public"."strategies_series" to "authenticated";

grant insert on table "public"."strategies_series" to "authenticated";

grant references on table "public"."strategies_series" to "authenticated";

grant select on table "public"."strategies_series" to "authenticated";

grant trigger on table "public"."strategies_series" to "authenticated";

grant truncate on table "public"."strategies_series" to "authenticated";

grant update on table "public"."strategies_series" to "authenticated";

grant delete on table "public"."strategies_series" to "service_role";

grant insert on table "public"."strategies_series" to "service_role";

grant references on table "public"."strategies_series" to "service_role";

grant select on table "public"."strategies_series" to "service_role";

grant trigger on table "public"."strategies_series" to "service_role";

grant truncate on table "public"."strategies_series" to "service_role";

grant update on table "public"."strategies_series" to "service_role";


  create policy "public read"
  on "public"."strategies_series"
  as permissive
  for select
  to public
using (true);



