
  create table "public"."trading_days" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "overnight" timestamp with time zone not null,
    "pre" timestamp with time zone not null,
    "regular" timestamp with time zone not null,
    "post" timestamp with time zone not null,
    "close" timestamp with time zone not null
      );


CREATE INDEX trading_days_close_idx ON public.trading_days USING btree (close);

CREATE UNIQUE INDEX trading_days_date_key ON public.trading_days USING btree (date);

CREATE UNIQUE INDEX trading_days_pkey ON public.trading_days USING btree (id);

CREATE INDEX trading_days_post_idx ON public.trading_days USING btree (post);

alter table "public"."trading_days" add constraint "trading_days_pkey" PRIMARY KEY using index "trading_days_pkey";

alter table "public"."trading_days" add constraint "trading_days_date_key" UNIQUE using index "trading_days_date_key";

grant delete on table "public"."trading_days" to "anon";

grant insert on table "public"."trading_days" to "anon";

grant references on table "public"."trading_days" to "anon";

grant select on table "public"."trading_days" to "anon";

grant trigger on table "public"."trading_days" to "anon";

grant truncate on table "public"."trading_days" to "anon";

grant update on table "public"."trading_days" to "anon";

grant delete on table "public"."trading_days" to "authenticated";

grant insert on table "public"."trading_days" to "authenticated";

grant references on table "public"."trading_days" to "authenticated";

grant select on table "public"."trading_days" to "authenticated";

grant trigger on table "public"."trading_days" to "authenticated";

grant truncate on table "public"."trading_days" to "authenticated";

grant update on table "public"."trading_days" to "authenticated";

grant delete on table "public"."trading_days" to "service_role";

grant insert on table "public"."trading_days" to "service_role";

grant references on table "public"."trading_days" to "service_role";

grant select on table "public"."trading_days" to "service_role";

grant trigger on table "public"."trading_days" to "service_role";

grant truncate on table "public"."trading_days" to "service_role";

grant update on table "public"."trading_days" to "service_role";


