
  create table "public"."allocations" (
    "id" bigint generated by default as identity not null,
    "holdings" jsonb not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."allocations" enable row level security;

CREATE UNIQUE INDEX allocations_pkey ON public.allocations USING btree (id);

CREATE INDEX idx_allocations_holdings ON public.allocations USING gin (holdings);

alter table "public"."allocations" add constraint "allocations_pkey" PRIMARY KEY using index "allocations_pkey";

grant delete on table "public"."allocations" to "anon";

grant insert on table "public"."allocations" to "anon";

grant references on table "public"."allocations" to "anon";

grant select on table "public"."allocations" to "anon";

grant trigger on table "public"."allocations" to "anon";

grant truncate on table "public"."allocations" to "anon";

grant update on table "public"."allocations" to "anon";

grant delete on table "public"."allocations" to "authenticated";

grant insert on table "public"."allocations" to "authenticated";

grant references on table "public"."allocations" to "authenticated";

grant select on table "public"."allocations" to "authenticated";

grant trigger on table "public"."allocations" to "authenticated";

grant truncate on table "public"."allocations" to "authenticated";

grant update on table "public"."allocations" to "authenticated";

grant delete on table "public"."allocations" to "service_role";

grant insert on table "public"."allocations" to "service_role";

grant references on table "public"."allocations" to "service_role";

grant select on table "public"."allocations" to "service_role";

grant trigger on table "public"."allocations" to "service_role";

grant truncate on table "public"."allocations" to "service_role";

grant update on table "public"."allocations" to "service_role";


  create policy "public read"
  on "public"."allocations"
  as permissive
  for select
  to public
using (true);



