
  create table "public"."tickers" (
    "id" bigint generated by default as identity not null,
    "symbol" text not null,
    "leverage" numeric not null
      );


CREATE UNIQUE INDEX tickers_pkey ON public.tickers USING btree (id);

CREATE UNIQUE INDEX tickers_symbol_leverage_key ON public.tickers USING btree (symbol, leverage);

alter table "public"."tickers" add constraint "tickers_pkey" PRIMARY KEY using index "tickers_pkey";

alter table "public"."tickers" add constraint "tickers_symbol_leverage_key" UNIQUE using index "tickers_symbol_leverage_key";

grant delete on table "public"."tickers" to "anon";

grant insert on table "public"."tickers" to "anon";

grant references on table "public"."tickers" to "anon";

grant select on table "public"."tickers" to "anon";

grant trigger on table "public"."tickers" to "anon";

grant truncate on table "public"."tickers" to "anon";

grant update on table "public"."tickers" to "anon";

grant delete on table "public"."tickers" to "authenticated";

grant insert on table "public"."tickers" to "authenticated";

grant references on table "public"."tickers" to "authenticated";

grant select on table "public"."tickers" to "authenticated";

grant trigger on table "public"."tickers" to "authenticated";

grant truncate on table "public"."tickers" to "authenticated";

grant update on table "public"."tickers" to "authenticated";

grant delete on table "public"."tickers" to "service_role";

grant insert on table "public"."tickers" to "service_role";

grant references on table "public"."tickers" to "service_role";

grant select on table "public"."tickers" to "service_role";

grant trigger on table "public"."tickers" to "service_role";

grant truncate on table "public"."tickers" to "service_role";

grant update on table "public"."tickers" to "service_role";


