
  create table "public"."indicators_series" (
    "id" bigint generated by default as identity not null,
    "indicator_id" bigint not null,
    "trading_day_id" bigint not null,
    "value" numeric not null,
    "metadata" jsonb
      );


CREATE INDEX indicators_series_indicator_id_idx ON public.indicators_series USING btree (indicator_id);

CREATE UNIQUE INDEX indicators_series_pkey ON public.indicators_series USING btree (id);

CREATE INDEX indicators_series_trading_day_id_idx ON public.indicators_series USING btree (trading_day_id);

CREATE UNIQUE INDEX unique_indicator_eval_per_day ON public.indicators_series USING btree (indicator_id, trading_day_id);

alter table "public"."indicators_series" add constraint "indicators_series_pkey" PRIMARY KEY using index "indicators_series_pkey";

alter table "public"."indicators_series" add constraint "indicators_series_indicator_id_fkey" FOREIGN KEY (indicator_id) REFERENCES public.indicators(id) ON DELETE CASCADE not valid;

alter table "public"."indicators_series" validate constraint "indicators_series_indicator_id_fkey";

alter table "public"."indicators_series" add constraint "indicators_series_trading_day_id_fkey" FOREIGN KEY (trading_day_id) REFERENCES public.trading_days(id) ON DELETE CASCADE not valid;

alter table "public"."indicators_series" validate constraint "indicators_series_trading_day_id_fkey";

alter table "public"."indicators_series" add constraint "unique_indicator_eval_per_day" UNIQUE using index "unique_indicator_eval_per_day";

grant delete on table "public"."indicators_series" to "anon";

grant insert on table "public"."indicators_series" to "anon";

grant references on table "public"."indicators_series" to "anon";

grant select on table "public"."indicators_series" to "anon";

grant trigger on table "public"."indicators_series" to "anon";

grant truncate on table "public"."indicators_series" to "anon";

grant update on table "public"."indicators_series" to "anon";

grant delete on table "public"."indicators_series" to "authenticated";

grant insert on table "public"."indicators_series" to "authenticated";

grant references on table "public"."indicators_series" to "authenticated";

grant select on table "public"."indicators_series" to "authenticated";

grant trigger on table "public"."indicators_series" to "authenticated";

grant truncate on table "public"."indicators_series" to "authenticated";

grant update on table "public"."indicators_series" to "authenticated";

grant delete on table "public"."indicators_series" to "service_role";

grant insert on table "public"."indicators_series" to "service_role";

grant references on table "public"."indicators_series" to "service_role";

grant select on table "public"."indicators_series" to "service_role";

grant trigger on table "public"."indicators_series" to "service_role";

grant truncate on table "public"."indicators_series" to "service_role";

grant update on table "public"."indicators_series" to "service_role";


