create type "public"."comparison" as enum ('>', '<', '=');


  create table "public"."signals" (
    "id" bigint generated by default as identity not null,
    "indicator_id_1" bigint not null,
    "indicator_id_2" bigint not null,
    "comparison" public.comparison not null,
    "tolerance" numeric not null
      );


CREATE UNIQUE INDEX signals_pkey ON public.signals USING btree (id);

CREATE UNIQUE INDEX unique_signal_definition ON public.signals USING btree (indicator_id_1, indicator_id_2, comparison, tolerance);

alter table "public"."signals" add constraint "signals_pkey" PRIMARY KEY using index "signals_pkey";

alter table "public"."signals" add constraint "signals_indicator_id_1_fkey" FOREIGN KEY (indicator_id_1) REFERENCES public.indicators(id) ON DELETE CASCADE not valid;

alter table "public"."signals" validate constraint "signals_indicator_id_1_fkey";

alter table "public"."signals" add constraint "signals_indicator_id_2_fkey" FOREIGN KEY (indicator_id_2) REFERENCES public.indicators(id) ON DELETE CASCADE not valid;

alter table "public"."signals" validate constraint "signals_indicator_id_2_fkey";

alter table "public"."signals" add constraint "unique_signal_definition" UNIQUE using index "unique_signal_definition";

grant delete on table "public"."signals" to "anon";

grant insert on table "public"."signals" to "anon";

grant references on table "public"."signals" to "anon";

grant select on table "public"."signals" to "anon";

grant trigger on table "public"."signals" to "anon";

grant truncate on table "public"."signals" to "anon";

grant update on table "public"."signals" to "anon";

grant delete on table "public"."signals" to "authenticated";

grant insert on table "public"."signals" to "authenticated";

grant references on table "public"."signals" to "authenticated";

grant select on table "public"."signals" to "authenticated";

grant trigger on table "public"."signals" to "authenticated";

grant truncate on table "public"."signals" to "authenticated";

grant update on table "public"."signals" to "authenticated";

grant delete on table "public"."signals" to "service_role";

grant insert on table "public"."signals" to "service_role";

grant references on table "public"."signals" to "service_role";

grant select on table "public"."signals" to "service_role";

grant trigger on table "public"."signals" to "service_role";

grant truncate on table "public"."signals" to "service_role";

grant update on table "public"."signals" to "service_role";


